### ISSUE TITLE
Add COX to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#107]
Add logo and metadata for COX

**Comment by aarondonwilliams** [comment]
[Cox_Communications_Logo.svg.zip](https://github.com/lf-edge-landscape/lfedge-landscape/files/4141874/Cox_Communications_Logo.svg.zip)

**Comment by aarondonwilliams** [comment]
I am assuming that this is for Cox Communications.

**Comment by aarondonwilliams** [comment]
[cox.svg.zip](https://github.com/lf-edge-landscape/lfedge-landscape/files/4141889/cox.svg.zip)

**Comment by aarondonwilliams** [comment]
Category: Wireless & Wired- Wired
item:
            name: Cox Communications
            homepage_url: 'https://cox.com/'
            logo: cox.svg
            crunchbase: 'https://www.crunchbase.com/organization/cox-communications'

**Comment by aarondonwilliams** [comment]
Will be closed by PR 369
