### ISSUE TITLE
Add Level 3 to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#152]
Add logo and metadata for Level 3

**Comment by aarondonwilliams** [comment]
CenturyLink purchased them and I don't see century link on the landscape, I am going to use century link's logo and details

**Comment by aarondonwilliams** [comment]
CenturyLink seems more like a Comcast or Verizon vs. Level 3 was CDN

**Comment by ninjaginja** [comment]
This is certainly one of those interesting ones that spans across several categories. They do have some stand-alone products that could probably be represented across categories. For example, their CDN Edge Compute product could go in the 'CDN & Distributed Caches' category, and the main CenturyLink logo could really be placed across both 'IAAS' and 'Wireline' categories.
