### ISSUE TITLE
Add Micron to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#160]
Add logo and metadata for Micron

**Comment by aarondonwilliams** [comment]
should be completed by PR 371

**Comment by aarondonwilliams** [comment]
- item:
            name: Micron Technology
            homepage_url: 'https://www.micron.com/'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Micron_Technology_logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/micron-technology'

**Comment by aaronLFEdge** [comment]
closed by PR 371
