### ISSUE TITLE
Add Siemens to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#182]
Add logo and metadata for Siemens

**Comment by aarondonwilliams** [comment]
putting this in Real Estate - traditional.  Siemens is like EATON or like GE, a massive company that products everything.

**Comment by aarondonwilliams** [comment]
- item:
            name: Siemens
            homepage_url: 'https://new.siemens.com/global/en.html'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Siemens-logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/siemens'

**Comment by aarondonwilliams** [comment]
PR  #375
