### ISSUE TITLE
Add Silverpeak to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#183]
Add logo and metadata for Silverpeak

**Comment by aarondonwilliams** [comment]
HPE has announced an intent to purchase them...

**Comment by aarondonwilliams** [comment]
putting this in Networking/networking- the do WAN

- item:
            name: Silver Peak
            homepage_url: 'https://www.silver-peak.com/'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/5/54/Silver_Peak_logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/silver-peak'

**Comment by aarondonwilliams** [comment]
PR #375
