### ISSUE TITLE
Add SoftBank to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#184]
Add logo and metadata for SoftBank

**Comment by aarondonwilliams** [comment]
Wireless and Wired
wired

- item:
            name: SoftBank
            homepage_url: 'https://www.softbank.jp/en/'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/Softbank_logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/softbank'

**Comment by aarondonwilliams** [comment]
This will be fixed by PR #367

**Comment by aaronLFEdge** [comment]
softbank is on the landscape.
