### ISSUE TITLE
Add Supermicro to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#188]
Add logo and metadata for Supermicro

**Comment by aaronLFEdge** [comment]
- Edge OEMS

 - item:
            name: Supermicro
            homepage_url: 'https://www.supermicro.com/en/'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Super_Micro_Computer_Logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/super-micro-computer'

**Comment by aaronLFEdge** [comment]
done...
