### ISSUE TITLE
Add T-Mobile to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#189]
Add logo and metadata for T-Mobile

**Comment by aaronLFEdge** [comment]
https://upload.wikimedia.org/wikipedia/commons/4/42/T-Mobile-Logo.svg

**Comment by aaronLFEdge** [comment]
Networking--> Networking

- item:
            name: T-Mobile
            homepage_url: 'https://www.t-mobile.com/'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/4/42/T-Mobile-Logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/t-mobile'

**Comment by aaronLFEdge** [comment]
completed
