### ISSUE TITLE
Add Telefonnica to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#190]
Add logo and metadata for Telefonnica

**Comment by aaronLFEdge** [comment]
- item:
            name: Telefonica
            homepage_url: 'https://www.telefonica.com/en/home'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/0/0a/Telefonica-Europe-Logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/telefonica'

**Comment by aarondonwilliams** [comment]
should be closed by #366

**Comment by aaronLFEdge** [comment]
telefonica is on the landscape closing this
