### ISSUE TITLE
Add Telia to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#191]
Add logo and metadata for Telia

**Comment by aarondonwilliams** [comment]
add to Wireless and wireline- wireless
- item:
            name: Telia Company
            homepage_url: 'https://www.teliacompany.com/en'
            logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a5/Telia_Company_Logo.svg'
            crunchbase: 'https://www.crunchbase.com/organization/teliasonera'

**Comment by aarondonwilliams** [comment]
should be completed by PR #376

**Comment by aarondonwilliams** [comment]
PR #376
