### ISSUE TITLE
Add instructions and/or links for adding/correcting on home of landscape.lfedge.org

### ISSUE THREAD

**Issue by mtrifiro** [State-of-the-Edge/lfedge-landscape#314]
Visitors to landscape.lfedge.org have no way of knowing how to improve the landscape because the home page of the landscape does not include any such info. Can we add some helpful instructions and links to the left sidebar?

**Comment by wesreisz** [comment]
@mtrifiro That's a good point... I'll take a look. Right off, I'm thinking there's some text as that top we might be able to add. Will look through and see about a suggestion.

**Comment by wesreisz** [comment]
Added... it's still not the clearest. We can discuss additional steps on the bi-weekly call if this isn't clear enough.
