### ISSUE TITLE
Ad rotation in sidebar should be LF Edge focused

### ISSUE THREAD

**Issue by mtrifiro** [State-of-the-Edge/lfedge-landscape#315]
There appears to be an "ad" in the left sidebar at landscape.lfedge.org. The ad currently showing is for Kubecon and CNCF. I suggest this could be more edge relevant.

![image](https://user-images.githubusercontent.com/3193268/78816188-37fb0e00-7986-11ea-9565-2d131430a50b.png)

**Comment by wesreisz** [comment]
Created a new image for the State of the Edge report and pointed to the lfedge edge page on it:
https://github.com/State-of-the-Edge/lfedge-landscape/pull/324

Image is pretty simple. We can replace with something new if desired.
![state_of_edge_2020](https://user-images.githubusercontent.com/3803036/79877034-bf4e7580-83b9-11ea-924a-bba27093b9df.png)
