### ISSUE TITLE
Logo: update Packet logo

### ISSUE THREAD

**Issue by vielmetti** [State-of-the-Edge/lfedge-landscape#316]
Packet has a new logo, which can be found on the CNCF landscape as

https://github.com/cncf/landscape/blob/master/hosted_logos/packet.svg

Thanks to @taylorwaggoner for helping update that in the CNCF space - I am not 100% sure of process for updating that here as well.

**Comment by vielmetti** [comment]
@mhall119 @mtrifiro any recommendations for process here? thanks!

**Comment by wesreisz** [comment]
Done and merged.
