### ISSUE TITLE
fix for ThunderSoft description 

### ISSUE THREAD

**Issue by pczou** [State-of-the-Edge/lfedge-landscape#345]
this is CTO & SVP of ThunderSoft, would like to request the following change to "Thunder Software"

please use "**ThunderSoft**" as the name of the company, not "Thunder Software".

**Thundersoft Company offers mobile internet terminal products and operating systems through integrated mobile and IoT terminal solutions.**

Website
thundersoft.com

Crunchbase
crunchbase.com/organization/thundersoft-company-limited

LinkedIn
linkedin.com/company/thundersoft

Twitter
@ThunderSoft_Ltd

Headquarters
Beijing, China

Headcount
**5000-10,000**

Market Cap
$3.59B

**Comment by ninjaginja** [comment]
Thanks @pczou  - just merged the update.
