### ISSUE TITLE
Add APC to LF-Edge lanscape

### ISSUE THREAD

**Issue by mhall119** [State-of-the-Edge/lfedge-landscape#87]
Add logo and metadata for APC

**Comment by bprestonlf** [comment]
https://drive.google.com/open?id=1C2E8WZvGFT5Oes8NUtqvAAneFxiN7bRf

**Comment by aaronLFEdge** [comment]
infrasturcture--> physical
- item:
            name: APC
            homepage_url: 'https://www.apc.com/us/en/'
            logo: https://drive.google.com/open?id=1C2E8WZvGFT5Oes8NUtqvAAneFxiN7bRf
            crunchbase: 'https://www.crunchbase.com/organization/schneider-electric'

**Comment by aaronLFEdge** [comment]
completed with PR #341
